---
title: "xx_analysis_Christian"
format: html
editor: visual
---

## Analyses

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
data_clean_aug <- read_tsv("data/03_dat_aug.tsv.gz")
```

```{r}
stemcellsource_surv <- data_clean_aug |>
  mutate(surv_stat_fact = factor(survival_status, levels = c("Dead", "Alive"))) |>
  group_by(Stemcellsource, Disease, surv_stat_fact) |>
  summarise(N = n()) |>
  ggplot(aes(x = Stemcellsource, y = N, fill = surv_stat_fact)) +
  geom_col() +
  facet_wrap(~Disease)

stemcellsource_surv
```

```{r}
neutro_plot <- data_clean_aug |>
  filter(survival_status == "Dead") |>
  filter(ANCrecovery != 1000000) |>
  ggplot(aes(x = ANCrecovery, y = survival_time, colour = Disease)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Disease) +
  labs(title = "Time for neutrophil recovery and survival time", 
  x = "Time until neutophil recovery (>0.5 x 10^9/L) (days)", 
  y = "Survival time (days)")

neutro_plot
ggsave("neutrophils.png", width = 6)

platelet_plot <- data_clean_aug |>
  filter(survival_status == "Dead") |>
  filter(PLTrecovery != 1000000) |>
  ggplot(aes(x = PLTrecovery, y = survival_time, colour = Disease)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Disease) +
  labs(title = "Time for platelet recovery and survival time", 
  x = "Time until platelet recovery (>50000/mm3) (days)", 
  y = "Survival time (days)")

platelet_plot
ggsave("platelets.png", width = 6)
```

```{r}
neutro_surv_stat <- data_clean_aug |>
  filter(ANCrecovery != 1000000) |>
  ggplot(aes(x = Disease, y = ANCrecovery, fill = survival_status)) +
  geom_boxplot() +
  stat_cor()
neutro_surv_stat

platelet_surv_stat <- data_clean_aug |>
  filter(PLTrecovery != 1000000) |>
  ggplot(aes(x = Disease, y = PLTrecovery, fill = survival_status)) +
  geom_boxplot()
platelet_surv_stat
```
