---
title: "00_all"
format: 
  html:
    embed-resources: true
editor: visual
---

## Execute all scripts

Running load, clean, augment, describe, and analysis scripts.

Load library

```{r}
library(quarto)
library(here)
```

Render all scripts as HTML

```{r}
#| message: false
#| 
quarto_render("01_load.qmd", 
              output_file = "01_load.html", 
              output_format = "html")
quarto_render("02_clean.qmd", 
              output_file = "02_clean.html", 
              output_format = "html")
quarto_render("03_augment.qmd", 
              output_file = "03_augment.html", 
              output_format = "html")
quarto_render("04_describe.qmd", 
              output_file = "04_describe.html", 
              output_format = "html")
quarto_render("05_Analysis_Graft_vs_Host_disease.qmd", 
              output_file = "05_Analysis_Graft_vs_Host_diseased.html", 
              output_format = "html")
quarto_render("06_Analysis_Relapse_and_2nd_transplant_survival.qmd", 
              output_file = "06_Analysis_Relapse_and_2nd_transplant_survival.html", 
              output_format = "html")
quarto_render("07_Analysis_SCsource_recovery.qmd", 
              output_file = "07_Analysis_SCsource_recovery.html", 
              output_format = "html")
quarto_render("08_analysis_PCA_HLA.qmd", 
              output_file = "08_analysis_PCA_HLA.html", 
              output_format = "html")
quarto_render("09_Analysis_CD3_CD34.qmd", 
              output_file = "09_Analysis_CD3_CD34.html", 
              output_format = "html")
quarto_render("10_Analysis_Recipient.qmd", 
              output_file = "10_Analysis_Recipient.html", 
              output_format = "html")

```

Move HTML-files to correct folder

```{r}
html_quarto <- list.files(path = here("R"), pattern = "html")
file.rename(from = html_quarto, to = file.path(here("results"), html_quarto ))
```
