---
title: "02_Clean"
author: "Group 24"
format: html
editor: visual
---

## Clean data

Takes the bone-marrow.arff and creates a file consisting of a tibble with raw data and a text file containing the meta data

### Load libraries

```{r}
#| message: false
library(tidyverse)
library(here)

```

### Clean data

```{r}
# Get variable names and clean them
raw_data <- read_lines("data/_raw/bone-marrow.arff")
var_names <- raw_data |>
  str_subset("@attribute") |>
  str_remove_all(pattern = "@attribute|\\{.*\\}|numeric|\\s")

# get meta data and clean
meta_data <- raw_data |>
  str_subset("%") |>
  str_remove(pattern = "%")

# Create tibble
data_clean <- read_delim("data/_raw/bone-marrow.arff", 
                      delim = ",", 
                      # Start after line that starts with "@data"
                      skip = str_which(raw_data, pattern = "^@data")+1,
                      col_names = var_names,
                      na = "?",
                      col_types = "i"
                      )  |>
  mutate(across(c(1:2, 4:22, 24:28, 37), factor))

# write data to gzip tsv file 
data_clean |> write_tsv("data/02_dat_clean.tsv.gz")
meta_data |> write_lines("data/02_metadat_clean.txt.gz")

```
